import type { Migration } from "./scanner";

export const PRISMA_MIGRATION_SYNC_SCRIPT_NAME = "syncPrismaMigrations.ts";

export interface PrismaMigrationSyncScriptParams {
  outputMigrationName: string;
  outputSql: string;
  replacedMigrations: Pick<Migration, "name">[];
}

export function buildPrismaMigrationSyncScript(
  params: PrismaMigrationSyncScriptParams
): string {
  const replacedMigrationNames = [...new Set(params.replacedMigrations.map((m) => m.name))];

  return [
    'import { PrismaClient } from "@prisma/client";',
    'import { createHash } from "crypto";',
    'import { readFileSync } from "fs";',
    'import { join, dirname } from "path";',
    'import { fileURLToPath } from "url";',
    "",
    "const prisma = new PrismaClient();",
    "",
    `const squashedMigrationName = ${JSON.stringify(params.outputMigrationName)};`,
    `const replacedMigrationNames = ${JSON.stringify(replacedMigrationNames, null, 2)} as const;`,
    "",
    "function computeChecksum(): string {",
    "  const scriptDir = typeof __dirname !== 'undefined' ? __dirname : dirname(fileURLToPath(import.meta.url));",
    "  const migrationSqlPath = join(scriptDir, squashedMigrationName, 'migration.sql');",
    '  const sql = readFileSync(migrationSqlPath, "utf-8");',
    '  return createHash("sha256").update(sql).digest("hex");',
    "}",
    "",
    "function deterministicId(name: string): string {",
    '  const hex = createHash("sha256").update(name).digest("hex");',
    "  return [hex.slice(0, 8), hex.slice(8, 12), hex.slice(12, 16), hex.slice(16, 20), hex.slice(20, 32)].join('-');",
    "}",
    "",
    'type SupportedProvider = "mysql" | "postgresql" | "sqlite";',
    "",
    "function detectProvider(): SupportedProvider {",
    '  const databaseUrl = process.env.DATABASE_URL ?? "";',
    '  if (databaseUrl.startsWith("mysql://") || databaseUrl.startsWith("mysqls://")) {',
    '    return "mysql";',
    "  }",
    '  if (databaseUrl.startsWith("postgresql://") || databaseUrl.startsWith("postgres://") || databaseUrl.startsWith("cockroachdb://")) {',
    '    return "postgresql";',
    "  }",
    '  if (databaseUrl.startsWith("file:") || databaseUrl.startsWith("sqlite:")) {',
    '    return "sqlite";',
    "  }",
    '  throw new Error("Unsupported DATABASE_URL for generated _prisma_migrations sync script.");',
    "}",
    "",
    "function quoteIdentifier(provider: SupportedProvider, identifier: string): string {",
    '  if (provider === "mysql") {',
    '    return "`" + identifier.replace(/`/g, "``") + "`";',
    "  }",
    '  return "\\"" + identifier.replace(/"/g, \'""\') + "\\"";',
    "}",
    "",
    "function quoteLiteral(value: string): string {",
    '  return "\'" + value.replace(/\'/g, "\'\'") + "\'";',
    "}",
    "",
    "function currentTimestampExpression(provider: SupportedProvider): string {",
    '  return provider === "mysql" ? "CURRENT_TIMESTAMP(3)" : "CURRENT_TIMESTAMP";',
    "}",
    "",
    "async function checkTableExists(provider: SupportedProvider): Promise<boolean> {",
    '  if (provider === "mysql") {',
    "    const rows = await prisma.$queryRawUnsafe<Array<{ cnt: bigint }>>(",
    "      \"SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = '_prisma_migrations'\"",
    "    );",
    "    return rows.length > 0 && Number(rows[0]!.cnt) > 0;",
    "  }",
    "",
    '  if (provider === "postgresql") {',
    "    const rows = await prisma.$queryRawUnsafe<Array<{ cnt: bigint }>>(",
    "      \"SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = '_prisma_migrations'\"",
    "    );",
    "    return rows.length > 0 && Number(rows[0]!.cnt) > 0;",
    "  }",
    "",
    "  const rows = await prisma.$queryRawUnsafe<Array<{ cnt: number }>>(",
    "    \"SELECT COUNT(*) AS cnt FROM sqlite_master WHERE type='table' AND name='_prisma_migrations'\"",
    "  );",
    "  return rows.length > 0 && Number(rows[0]!.cnt) > 0;",
    "}",
    "",
    "async function readMigrationColumns(provider: SupportedProvider): Promise<Set<string>> {",
    '  if (provider === "mysql") {',
    "    const rows = await prisma.$queryRawUnsafe<Array<{ name: string }>>(",
    '      "SELECT COLUMN_NAME AS name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = \'_prisma_migrations\'"',
    "    );",
    "    return new Set(rows.map((row) => row.name));",
    "  }",
    "",
    '  if (provider === "postgresql") {',
    "    const rows = await prisma.$queryRawUnsafe<Array<{ name: string }>>(",
    '      "SELECT column_name AS name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = \'_prisma_migrations\'"',
    "    );",
    "    return new Set(rows.map((row) => row.name));",
    "  }",
    "",
    "  const rows = await prisma.$queryRawUnsafe<Array<{ name: string }>>(",
    '    "PRAGMA table_info(\'_prisma_migrations\')"',
    "  );",
    "  return new Set(rows.map((row) => row.name));",
    "}",
    "",
    "async function main(): Promise<void> {",
    "  const provider = detectProvider();",
    "",
    "  const tableExists = await checkTableExists(provider);",
    "  if (!tableExists) {",
    '    console.log("No _prisma_migrations table found (fresh database) — skipping sync.");',
    "    return;",
    "  }",
    "",
    '  const tableName = quoteIdentifier(provider, "_prisma_migrations");',
    "  const columns = await readMigrationColumns(provider);",
    "",
    '  if (!columns.has("migration_name")) {',
    '    throw new Error(\'Could not find the "migration_name" column on _prisma_migrations.\');',
    "  }",
    "",
    "  const squashedMigrationChecksum = computeChecksum();",
    "  const squashedMigrationId = deterministicId(squashedMigrationName);",
    "",
    "  await prisma.$transaction(async (tx) => {",
    "    const namesToReplace = [...new Set([...replacedMigrationNames, squashedMigrationName])];",
    "",
    "    if (namesToReplace.length > 0) {",
    "      const namesSql = namesToReplace.map((name) => quoteLiteral(name)).join(', ');",
    "      await tx.$executeRawUnsafe(",
    '        "DELETE FROM " +',
    "          tableName +",
    '          " WHERE " +',
    '          quoteIdentifier(provider, "migration_name") +',
    '          " IN (" +',
    "          namesSql +",
    '          ")"',
    "      );",
    "    }",
    "",
    "    const insertColumns: string[] = [];",
    "    const insertValues: string[] = [];",
    "",
    "    const pushColumn = (column: string, valueSql: string): void => {",
    "      if (!columns.has(column)) return;",
    "      insertColumns.push(quoteIdentifier(provider, column));",
    "      insertValues.push(valueSql);",
    "    };",
    "",
    '    pushColumn("id", quoteLiteral(squashedMigrationId));',
    '    pushColumn("checksum", quoteLiteral(squashedMigrationChecksum));',
    '    pushColumn("migration_name", quoteLiteral(squashedMigrationName));',
    '    pushColumn("logs", quoteLiteral(""));',
    '    pushColumn("rolled_back_at", "NULL");',
    '    pushColumn("started_at", currentTimestampExpression(provider));',
    '    pushColumn("finished_at", currentTimestampExpression(provider));',
    '    pushColumn("applied_steps_count", "1");',
    "",
    "    if (insertColumns.length === 0) {",
    '      throw new Error("No supported columns were found on _prisma_migrations.");',
    "    }",
    "",
    "    await tx.$executeRawUnsafe(",
    '      "INSERT INTO " +',
    "        tableName +",
    '        " (" +',
    "        insertColumns.join(', ') +",
    '        ") VALUES (" +',
    "        insertValues.join(', ') +",
    '        ")"',
    "    );",
    "  });",
    "",
    '  console.log("Updated _prisma_migrations for " + squashedMigrationName);',
    "}",
    "",
    "main()",
    "  .catch(e => {",
    "    console.error(e);",
    "    process.exit(1);",
    "  })",
    "  .finally(() => {",
    "    console.log('Finished');",
    "    void prisma.$disconnect();",
    "  });",
    "",
  ].join("\n");
}
